---
- name: Disable EPEL repository
  ansible.builtin.yum_repository:
    name: epel
    state: absent

- name: Install requirements
  ansible.builtin.dnf:
    name:
      - chrony

- name: Configure services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - chronyd.service
